---
- name: Clone nvim
  git:
    dest: "{{ nvim_clone_path }}"
    repo: "{{ nvim_git_url }}"
    update: yes
    accept_hostkey: yes
    version: "{{ nvim_branch }}"

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=600
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install building tools (Debian)
  package:
    name:
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - make
      - g++
      - pkg-config
      - unzip
      - curl
    state: latest
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install building tools (RedHat)
  package:
    name:
      - ninja-build
      - libtool autoconf
      - automake
      - cmake
      - gcc
      - gcc-c++
      - make
      - pkgconfig
      - unzip
      - patch
      - gettext
      - curl
    state: latest
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Make clean
  shell:
    cmd: make distclean
    chdir: "{{ nvim_clone_path }}"

- name: Make build
  shell:
    cmd: make CMAKE_BUILD_TYPE=Release
    chdir: "{{ nvim_clone_path }}"

- name: Make install
  shell:
    cmd: make install
    chdir: "{{ nvim_clone_path }}"
