---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    pre_build_image: true
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible
